
platform :ios, '9.0'
target 'ygxtClass' do
pod 'AgoraRtcEngine_iOS'
pod 'AlipaySDK-iOS'
pod 'AFNetworking'
pod 'SocketRocket'

  pod 'FLAnimatedImage', '~> 1.0.12'
pod 'Masonry', '~> 1.1.0'

#pod 'SDCycleScrollView', '~> 1.75'

end
